version: "3"
services:
  api:
    image: "typeorm-api:production"
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        ENV: production
    environment:
      ENV: production
    env_file:
      - ".env.production"
    # This command will overwrite what is contained in the Dockerfile
    command: "npm run start:production"
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
