version: "3"
services:
  api_test:
    image: "typeorm-api:test" 
    container_name: "typeorm-api-test"
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - "./package.json:/app/package.json" # Will overwrite local package.json file
    environment:
      ENV: test
      REDIS_HOST: "redis_test"
    command: "npm run start:test"
    stdin_open: true
    tty: true
    env_file:
      - ".env.test"
    depends_on:
      - db_test
      - redis_test
    networks:
      - typeorm_test
  db_test:
    image: "postgres:13.2-alpine"
    container_name: db_test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./postgres/test/data:/var/lib/postgresql/data:delegated"
    networks:
      - typeorm_test
  redis_test:
    image: "redis:alpine"
    container_name: redis_test
    volumes: 
      - "./redis/test/data:/var/lib/redis"
    networks:
      - typeorm_test
networks:
  typeorm_test:
