version: "3"
services:
  api:
    image: "typeorm-api:development" 
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        ENV: development
    environment:
      ENV: development
    env_file:
      - ".env.development"
    depends_on:
      - db
  db:
    image: "postgres:9.6"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./postgres/development/data:/var/lib/postgresql/data:delegated"
    ports:
      - "5432:5432"
