version: "3"
services:
  api:
    container_name: "typeorm-api"
    image: "typeorm-api:${ENV}"
    # Mount the source container so that changes are re-built
    volumes:
      - ./src:/app/src
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ".env.${ENV}"
    ports:
      - '3000:3000'
