version: "3"
services:
  api:
    image: "typeorm-api:development" 
    container_name: "typeorm-api"
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - "./package.json:/app/package.json" # Will overwrite local package.json file
    ports:
      - "${PORT}:1234"
    environment:
      ENV: development
      PORT: "${PORT}"
    env_file:
      - ".env.development"
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: "postgres:13.2-alpine"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./postgres/development/data:/var/lib/postgresql/data:delegated"
    ports:
      - "5432:5432"
  redis:
    image: "redis:6.2.0-alpine"
    container_name: redis
    volumes: 
      - "./redis/development/data:/var/lib/redis"
    expose:
      - 6379
