version: "3"
services:
  api_dev:
    image: "typeorm-api:development" 
    container_name: "typeorm-api"
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - "./package.json:/app/package.json" # Will overwrite local package.json file
    ports:
      - "${PORT}:1234"
    environment:
      ENV: development
      PORT: "${PORT}"
      REDIS_HOST: "redis_dev"
    env_file:
      - ".env.development"
    depends_on:
      - db_dev
      - redis_dev
    restart: always
    networks:
      - typeorm_development
  db_dev:
    image: "postgres:13.2-alpine"
    container_name: db_dev
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./postgres/development/data:/var/lib/postgresql/data:delegated"
    networks:
      - typeorm_development
  redis_dev:
    image: "redis:6.2.0-alpine"
    container_name: redis_dev
    volumes: 
      - "./redis/development/data:/var/lib/redis"
    networks:
      - typeorm_development
networks:
  typeorm_development:
