version: "3"
services:
  api:
    image: "typeorm-api:development" 
    container_name: "typeorm-api"
    volumes:
      - ./src:/app/src
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        PORT: "${PORT}"
    environment:
      PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
