apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master # Unique name for the deployment
  labels:
    app: redis # Label applied to deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template: # Template for the pods that will be created by this deployment
    metadata:
        labels:
          app: redis
    spec:
      containers:
        - name: master
          image: redis
          ports:
            - containerPort: 6379
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-master # Name of resource (service resource) for others to connect to, aka redis-master:6379
  labels:
    app: redis 
spec:
  type: ClusterIP
  ports:
  - port: 6379 # Map incoming connections on port 6379 to 6379 of the pod
    targetPort: 6379
  selector:
    app: redis # Apply this to pods which match this label
